ALTER TABLE `Compra`
  MODIFY `ProductoServicio` VARCHAR(255) NULL DEFAULT NULL,
  MODIFY `Cantidad` DECIMAL(10,2) NULL DEFAULT NULL,
  MODIFY `PrecioUnitario` DECIMAL(12,2) NULL DEFAULT NULL;

ALTER TABLE `Gasto`
  MODIFY `Descripcion` VARCHAR(500) NULL DEFAULT NULL;
